# Generated by Django 5.1.2 on 2024-10-13 16:20

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="post",
            managers=[
                ("post_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
