# Generated by Django 5.1.2 on 2024-10-13 16:49

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("active_user_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
